### ISSUE TITLE
Availability on Curseforge for modpack makers?

### ISSUE THREAD

**Issue by BurningSulphur** [davidjjung/framechanger#3]
I'd like to add this to my modpack but it's only available on modrinth so I can't share my pack with it installed

**Comment by davidjjung** [comment]
Apologies, but I have no intent on uploading the mod to Curseforge at this time. Curseforge does have a list of mods that are slowly being approved outside of its own ecosystem, but mods like mine are very small and probably would not be introduced to that ecosystem for a while.

The best compromise currently available is to include the config files for Frame Changer in your pack, and stating that the mod can be installed separately by players who wish to use it. (This is what the modpack Raspberry Flavoured does with my mod Milky Way, for example). I understand that it's not optimal, but I have next-to-no interest in supporting Curseforge. Cheers, lmk if you have any other questions
